### ISSUE TITLE
[Bug report] Too much detection distance can cause the game to lag periodically

### ISSUE THREAD

**Issue by xisnoDy** [Dankan37/Arma-3-Iron-Dome#1] opened 2024-01-12 20:12 UTC
When running this mod in the current version of Arma3 (I don't know if this problem exists in older versions as well), the game periodically stutters every few seconds when the trigger distance is set to be greater than 4000 meters. 

I think this issue is related to the code associated with detecting flying objects within range. The problem seems to have been there from the start, it's just that its effects are less noticeable when the detection distance is small. The problems caused by this bug are very disruptive to the gameplay experience. When the detection distance reaches 10,000 meters, there is a noticeable lag almost every two seconds.

**Comment by Dankan37** [comment] 2024-01-14 21:36
Yes, I made this stuff some time back and the issue is due to the fact is runs:
`_near = _unit nearObjects [_typeArray select _i, _distance];`
inside a isNil, forcing it run in a unscheduled environment, I don't recall the reasons why I chose this, a fix could be to schedule it, I'm currently not maintaining my mods but I may try to look into it, anyway the mods are released to the public.

**Comment by Dankan37** [comment] 2024-09-06 09:24
fixed with the newest EH

**Closed as completed by Dankan37** 2024-09-06 09:24 UTC
